### PR TITLE
Upgrade to Symfony 2.7 LTS

### PR DESCRIPTION
**Pull request by rjkip**

### CODE REVIEW

**Comment by rjkip** [comment]
:sparkles: @DRvanR :sparkles:

**Comment by DRvanR** [comment]
:+1:

**Comment by rjkip** [comment]
Some changes required after choice lists thingies :bomb: @DRvanR

**Comment by rjkip** [comment]
:star2: @DRvanR

**Comment by DRvanR** [comment]
:+1:

**Pull request merged**
